export const BAY_AREA_CITIES = [
  "Antioch",
  "Berkeley",
  "Concord",
  "Daly City",
  "Fremont",
  "Hayward",
  "Livermore",
  "Mountain View",
  "Palo Alto",
  "Oakland",
  "Redwood City",
  "Richmond",
  "San Francisco",
  "San Jose",
  "San Leandro",
  "San Mateo",
  "Santa Clara",
  "Santa Rosa",
  "Sunnyvale",
  "Vallejo",
  "Walnut Creek",
];
